name: Python Package with Rubin Science Pipelines

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  HOME: /home/lsst

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack:
          - ghcr.io/lsst/scipipe:al9-w_latest

    container: ${{ matrix.stack }}

    steps:
    - name: Setup Environment
      run: |
        cd $HOME
        echo "source /opt/lsst/software/stack/loadLSST.bash" >> .bashrc
        echo "setup lsst_distrib" >> .bashrc
        echo "cd $HOME" >> $HOME/.bashrc
    - name: Install git
      shell: bash -l {0}
      run: |
        gittest=`conda list git | grep git`
        if [ -z "$gittest" ]; then
            conda install -y git
        fi
    - name: Check out code
      shell: bash -l {0}
      run: |
        git clone https://github.com/${GITHUB_REPOSITORY}
        cd the_monster
        git fetch origin ${GITHUB_REF}:TESTING
        git checkout TESTING
        echo "cd ${PWD}" >> $HOME/.bashrc
        echo "setup -j -r ." >> $HOME/.bashrc
    - name: Test with scons
      shell: bash -l {0}
      run: |
        scons
